---
- name: Hello World!
  hosts: all
  vars:
   timezone: America/New_York
  roles:
    - huxoll.azure-cli
  tasks:
  - debug:
      var=subscription_id
  - name: Hello World!
    shell: echo "Hi! Tower is working."
    
  - name: Print some debug information 
    vars: 
      msg: |
        Module Variables ("vars"):
        --------------------------------
        {{ vars | to_nice_json }} 

        Environment Variables ("environment"):
        --------------------------------
        {{ environment | to_nice_json }} 

        GROUP NAMES Variables ("group_names"):
        --------------------------------
        {{ group_names | to_nice_json }}

        GROUPS Variables ("groups"):
        --------------------------------
        {{ groups | to_nice_json }}

        HOST Variables ("hostvars"):
        --------------------------------
        {{ hostvars | to_nice_json }} 

    debug: 
      msg: "{{ msg.split('\n') }}"       
    tags: debug_info
  - name: az login
    shell: az login -u {{ansible_env.AZURE_AD_USER}} -p {{ansible_env.AZURE_PASSWORD}}
